# Generated by Django 6.0.5 on 2026-07-22 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('focus', 'Focus'), ('streak', 'Streak'), ('xp', 'XP'), ('tasks', 'Tasks')], max_length=20)),
                ('icon', models.CharField(default='Trophy', max_length=50)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement')],
            },
        ),
    ]
