# Generated by Django 6.0.5 on 2026-07-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('focus_session', 'Focus Session'), ('achievement', 'Achievement'), ('daily_goal', 'Daily Goal'), ('streak', 'Streak'), ('system', 'System')], default='focus_session', max_length=30)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='Optional ID of the object that generated this XP.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='leaderboard_user_id_5e64c3_idx')],
            },
        ),
    ]
