# Generated by Django 6.0.5 on 2026-07-23 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='pause_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of pauses during the session'),
        ),
        migrations.CreateModel(
            name='StopwatchLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(help_text='Lap duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='focus.focussession')),
            ],
            options={
                'ordering': ['lap_number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'lap_number'), name='unique_lap_per_session')],
            },
        ),
    ]
